demo:
  name: meteatbas
  email: meteatbas@gmail.com
  repositoryName: https://github.com/meteatbas/parcialSeven
  filePath: //desktop-6ujvr85/Users/meteatbas/Documents/projectPartialSeven/
  gitUsername: meteaghg
  gitPassword: ghhgfhgf